name:
  chocolateorange

url:
  http://www.sasaplus1.com

timezone:
  Asia/Tokyo

markdown:
  kramdown

highlighter:
  rouge

kramdown:
  input: GFM

sass:
  style: compressed

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - vendor
